CREATE TABLE IF NOT EXISTS guia_de_acoes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sigla VARCHAR(20) NOT NULL,
    setor VARCHAR(255) NULL,
    cotacao DOUBLE NULL,
    pt_projetivo DOUBLE NULL,
    pt_medio DOUBLE NULL,
    preco_consenso DOUBLE NULL,
    part_ibov DOUBLE NULL,
    val_mercado DOUBLE NULL,
    vol_med_3m DOUBLE NULL,
    retorno_ano DOUBLE NULL,
    retorno_12m_prov DOUBLE NULL,
    retorno_12m_sem_prov DOUBLE NULL,
    retorno_36m_prov DOUBLE NULL,
    retorno_36m_sem_prov DOUBLE NULL,
    retorno_60m_prov DOUBLE NULL,
    retorno_60m_sem_prov DOUBLE NULL,
    dpa_medio DOUBLE NULL,
    dy_medio DOUBLE NULL,
    dy_12m DOUBLE NULL,
    prov_p_acao_12m DOUBLE NULL,
    dt_ultimo_prov DATE,
    projecao_div DOUBLE NULL,
    dy_projetivo DOUBLE NULL,
    dif_mercado_pt_projetivo DOUBLE NULL,
    pm_pt_projetivo DOUBLE NULL,
    payout_medio DOUBLE NULL,
    projecao_lucro DOUBLE NULL,
    qtde_acoes DOUBLE NULL,
    projecao_lpa DOUBLE NULL,
    vpa DOUBLE NULL,
    p_vpa DOUBLE NULL,
    p_l DOUBLE NULL,
    ev DOUBLE NULL,
    ev_ebitda DOUBLE NULL,
    ebitda DOUBLE NULL,
    div_bruta DOUBLE NULL,
    div_liquida DOUBLE NULL,
    caixa DOUBLE NULL,
    div_liquida_ebitda DOUBLE NULL,
    lucro_liquido DOUBLE NULL,
    lpa DOUBLE NULL,
    margem_ebitda DOUBLE NULL,
    margem_liquida DOUBLE NULL,
    roe DOUBLE NULL,
    roic DOUBLE NULL,
    ev_ebit DOUBLE NULL,
    market_value_at DOUBLE NULL,
    psr DOUBLE NULL,
    market_value_acpc DOUBLE NULL,
    market_value_ac_pc_pnc DOUBLE NULL,
    fcfpa DOUBLE NULL,
    fcfy DOUBLE NULL,
    div_liqui_pl DOUBLE NULL,
    div_liqui_ebitda DOUBLE NULL,
    lc DOUBLE NULL,
    margem_bruta_pct DOUBLE NULL,
    roa DOUBLE NULL,
    cagr_receita DOUBLE NULL,
    cagr_lucro DOUBLE NULL,
    cagr_div DOUBLE NULL,
    cotacao_fechamento DOUBLE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_guia_de_acoes_sigla (sigla),
    KEY idx_guia_de_acoes_setor (setor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
